import Head from 'next/head';
import Image from 'next/image';
import mainBanner from '../assets/img/rickandmortybanner.png';

export default function Home() {
   return (
      <>
         <Head>
            <title>Rick & Morty - GraphQL Training</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/rickfavicon.png" />
         </Head>
         <main className="home-container">
            {/* <Image
               src={mainBanner}
               alt="Website main banner featuring Rick and Morty"
               priority
               placeholder="blur"
            /> */}
            <h1 className="main-title">Rick and Morty GraphQL Training</h1>
         </main>
      </>
   );
}
