import Head from 'next/head';
import MainTitle from '../components/MainTitle/MainTitle';

export default function Home() {
   return (
      <>
         <Head>
            <title>Rick & Morty - GraphQL Training</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/rickfavicon.png" />
         </Head>
         <main className="home-container">
            <MainTitle content="Rick & Morty GraphQL training" />
         </main>
      </>
   );
}
